### ISSUE TITLE
Thunderbolt 3 eGPU did not work properly

### ISSUE THREAD

**Issue by AndyTQ** [AsahiHuang/ThinkPadP51-Hackintosh-Catalina#1]
Hi, 

I am trying to get my eGPU (Radeon RX 5700 XT) working on P51 (the 5700XT is connected to an external monitor). However, when I am booting up (with the eGPU plugged into TB3 before booting), it got stuck at apple logo. Further investigation with -v shows that there are some ACPI exceptions. A screenshot is shown as follow. 

**However, when I boot WITHOUT eGPU plugging in before booting, the machine works perfectly. (with integrated GPU, but clearly in this case I cannot connect to externa monitors.)** 

EFI is the same as the one in the repo. 

Apprciate any help. 

Thanks!

![WeChat Image_20191225175917](https://user-images.githubusercontent.com/27390240/71449216-860d3e00-2716-11ea-96b9-b5e14d589ec7.jpg)

**Comment by AndyTQ** [comment]
UPDATE:
It seems that I currently have an imperfect workaround, which gets the external monitors working for my 5700XT navi card by **disabling iGPU:**

1. Change SMBIOS to iMacPro1, 1 (This is specific for my RX5700XT card, as mentioned in https://www.tonymacx86.com/threads/rx-5700-xt-compatibility.285798/. 
For older cards such as RX 570/580, you probably won't need to do this, according to https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme). However, feel free to try both :)
2. Add boot flag **agdpmod=pikera**
3. Disable iGPU in BIOS, i.e. changing hybrid graphics to discrete graphics.
4. As always, plug in the tb3 port **BEFORE** booting. 

But this workaround has a side effect: I have to switch it back to hybrid graphics in BIOS if I wanna move around :(  If I switch back to hybrid graphics in BIOS I still cannot use the eGPU :(

**Comment by AndyTQ** [comment]
A picture showing the workaround as described above.
![71485560-a9e88680-27df-11ea-80b9-f53fbbbd05d7](https://user-images.githubusercontent.com/27390240/164914692-5eabc567-fdc7-49d1-a5ae-84dd3d8b0158.jpeg)

**Comment by AndyTQ** [comment]
Another issue for eGPU is that if your P51 went to sleep, the external monitor won't wake up again. (And hence, both your laptop screen and monitors become black screen).  I think this is due to the fact that we haven't yet made it to the point where thunderbolt 3 ports can support hot plug for p51.

**Comment by AndyTQ** [comment]
Update: After 2 weeks of use, this method seems pretty stable. No severe bug found yet.

**Comment by huldarchen** [comment]
Hi,
When using eGPU (Radeon RX 5500 XT) on my p52 laptop (Mac OS 15.5.5), the graphics card is recognized normally, and the monitor prompts no signal.
![PCI](http://bbs.pcbeta.com/data/attachment/forum/202006/24/223330x5t225qqna39ik25.jpg)

![display](http://bbs.pcbeta.com/data/attachment/forum/202006/24/223351ftmwyk6flv9vv9zf.png)

Apprciate any help.

Thanks!

**Comment by AndyTQ** [comment]
> Hi,
> When using eGPU (Radeon RX 5500 XT) on my p52 laptop (Mac OS 15.5.5), the graphics card is recognized normally, and the monitor prompts no signal.
> ![PCI](https://camo.githubusercontent.com/e6af198586917a111b91cd0f3bd3aa24e1421eed/687474703a2f2f6262732e7063626574612e636f6d2f646174612f6174746163686d656e742f666f72756d2f3230323030362f32342f32323333333078357432323571716e613339696b32352e6a7067)
> 
> ![display](https://camo.githubusercontent.com/e4b1fc7ab07d3ea763bac84ec8adb25e536cadf4/687474703a2f2f6262732e7063626574612e636f6d2f646174612f6174746163686d656e742f666f72756d2f3230323030362f32342f32323333353166746d77796b36666c76397676397a662e706e67)
> 
> Apprciate any help.
> 
> Thanks!

Hello!

For P52, eGPU is handled differently, and it supports both Intel GPU + eGPU (which is better than P51).
You should check here:
https://github.com/liuyishengalan/ThinkPad-P52-P53-P72-P73-Hackintosh-10.15.x
